In [1]:
# Set the seed value for the notebook so the results are reproducible
from numpy.random import seed
seed(1)

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import pandas as pd

In [6]:
df=pd.read_csv('wide_quants1.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'wide_quants1.csv'

In [191]:
df['ROI_pct']=df['ROI_pct'].astype('int')

In [192]:
df=df[["budget","runtime","gross","ROI_pct","director"]]

In [193]:
df.head()

budget  runtime      gross  ROI_pct        director
0   8000000       89   52287414      553      Rob Reiner
1   6000000      103   70136369     1068     John Hughes
2  15000000      110  179800601     1098      Tony Scott
3  18500000      137   85160248      360   James Cameron
4   9000000       90   18564613      106  Randal Kleiser

In [194]:
# Step 0: Reformat data
data = df.values
X = data[:, 0:4]
y = data[:, 4]

In [195]:
y

array(['Rob Reiner', 'John Hughes', 'Tony Scott', ..., 'Steve Carr',
       'Kevin Reynolds', 'Sam Liu'], dtype=object)

In [196]:
X

array([[8000000, 89, 52287414, 553],
       [6000000, 103, 70136369, 1068],
       [15000000, 110, 179800601, 1098],
       ...,
       [8500000, 92, 19985196, 135],
       [20000000, 107, 36874745, 84],
       [3500000, 76, 3775000, 7]], dtype=object)

In [197]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

In [198]:
encoded_y

array([1507,  881, 1822, ..., 1688, 1021, 1596])

In [199]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: Rob Reiner
Encoded Label: 1507
------------
Original Class: John Hughes
Encoded Label: 881
------------
Original Class: Tony Scott
Encoded Label: 1822
------------
Original Class: James Cameron
Encoded Label: 717
------------
Original Class: Randal Kleiser
Encoded Label: 1456
------------
Original Class: Oliver Stone
Encoded Label: 1339
------------
Original Class: Jim Henson
Encoded Label: 815
------------
Original Class: David Lynch
Encoded Label: 383
------------
Original Class: Howard Deutch
Encoded Label: 674
------------
Original Class: David Cronenberg
Encoded Label: 366
------------
Original Class: Peter Faiman
Encoded Label: 1395
------------
Original Class: Russell Mulcahy
Encoded Label: 1580
------------
Original Class: David Seltzer
Encoded Label: 402
------------
Original Class: John Carpenter
Encoded Label: 856
------------
Original Class: Michael Mann
Encoded Label: 1223
------------
Original Class: Adrian Lyne
Encoded Label: 15
------------
Original Clas

------------
Original Class: Jon Turteltaub
Encoded Label: 930
------------
Original Class: Jerry Zaks
Encoded Label: 800
------------
Original Class: Edward Zwick
Encoded Label: 474
------------
Original Class: Woody Allen
Encoded Label: 1876
------------
Original Class: Paul Thomas Anderson
Encoded Label: 1375
------------
Original Class: Scott Hicks
Encoded Label: 1609
------------
Original Class: Rob Cohen
Encoded Label: 1499
------------
Original Class: Simon Wincer
Encoded Label: 1645
------------
Original Class: Julian Schnabel
Encoded Label: 975
------------
Original Class: Edward Burns
Encoded Label: 471
------------
Original Class: Matthew Bright
Encoded Label: 1177
------------
Original Class: Rick Friedberg
Encoded Label: 1491
------------
Original Class: David Koepp
Encoded Label: 380
------------
Original Class: Jean-Claude Van Damme
Encoded Label: 763
------------
Original Class: Tony Scott
Encoded Label: 1822
------------
Original Class: Gilbert Adler
Encoded Label: 599

Original Class: John Woo
Encoded Label: 920
------------
Original Class: Ridley Scott
Encoded Label: 1494
------------
Original Class: Steve Carr
Encoded Label: 1688
------------
Original Class: Roger Donaldson
Encoded Label: 1555
------------
Original Class: Gus Van Sant
Encoded Label: 637
------------
Original Class: Aaron Blaise
Encoded Label: 0
------------
Original Class: F. Gary Gray
Encoded Label: 505
------------
Original Class: John Whitesell
Encoded Label: 919
------------
Original Class: Adam Shankman
Encoded Label: 12
------------
Original Class: Martin Campbell
Encoded Label: 1161
------------
Original Class: Richard Donner
Encoded Label: 1473
------------
Original Class: Joe Dante
Encoded Label: 836
------------
Original Class: Carl Franklin
Encoded Label: 226
------------
Original Class: James Cox
Encoded Label: 718
------------
Original Class: Gary Fleder
Encoded Label: 560
------------
Original Class: Bobby Farrelly
Encoded Label: 174
------------
Original Class: David

Encoded Label: 1738
------------
Original Class: Nigel Cole
Encoded Label: 1321
------------
Original Class: Galt Niederhoffer
Encoded Label: 552
------------
Original Class: Dan Rush
Encoded Label: 327
------------
Original Class: Sngmoo Lee
Encoded Label: 1646
------------
Original Class: Wes Craven
Encoded Label: 1856
------------
Original Class: Tom Vaughan
Encoded Label: 1804
------------
Original Class: Adam Green
Encoded Label: 7
------------
Original Class: Tom Dey
Encoded Label: 1784
------------
Original Class: Kevin Munroe
Encoded Label: 1020
------------
Original Class: George Hickenlooper
Encoded Label: 587
------------
Original Class: Malcolm Venville
Encoded Label: 1104
------------
Original Class: Brad Peyton
Encoded Label: 180
------------
Original Class: Roger Kumble
Encoded Label: 1556
------------
Original Class: Brad Anderson
Encoded Label: 177
------------
Original Class: Lena Dunham
Encoded Label: 1066
------------
Original Class: Anthony Bell
Encoded Label: 96
-

In [200]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=1)

In [201]:
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler().fit(X_train)

In [202]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [203]:
from tensorflow.keras.utils import to_categorical
# One-hot encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)
y_train_categorical

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [204]:
encoded_y.shape

(4638,)

In [123]:
# One-hot encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)
y_train_categorical.shape

(3478, 1892, 2)

In [124]:
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler().fit(X_train)

In [125]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [126]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [127]:
from tensorflow.keras.layers import Dense
number_inputs = 3
number_hidden_nodes = 4
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))

In [128]:
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax'))

In [129]:
# Use categorical crossentropy for categorical data and mean squared error for regression
# Hint: your output layer in this example is using software for logistic regression (categorical)
# If your output layer activation was `linear` then you may want to use `mse` for loss
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [133]:
X_train_scaled.reshape(-1,1)

array([[-0.40172498],
       [-0.04705759],
       [-0.69351719],
       ...,
       [-1.25129116],
       [-0.68636293],
       [-0.03355761]])

In [134]:
y_train_categorical.reshape(-1,1)

array([[1.],
       [0.],
       [1.],
       ...,
       [0.],
       [1.],
       [0.]], dtype=float32)

In [135]:
# Fit (train) the model
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=1,
    shuffle=True,
    verbose=2
)

ValueError: in user code:

    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:747 train_step
        y_pred = self(x, training=True)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:212 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential_4 is incompatible with the layer: expected axis -1 of input shape to have value 3 but received input with shape [None, 4]


In [166]:
# Use train_test_split to create training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
X_train

array([[20000000],
       [80000000],
       [16000000],
       ...,
       [ 7400000],
       [12000000],
       [ 1100000]], dtype=int64)

In [167]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data
X_scaler = StandardScaler().fit(X_train)

X_train

array([[20000000],
       [80000000],
       [16000000],
       ...,
       [ 7400000],
       [12000000],
       [ 1100000]], dtype=int64)

In [168]:
# Transform the training and testing data using the X_scaler

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[-0.40172498],
       [ 1.10857254],
       [-0.50241148],
       ...,
       [-0.71888746],
       [-0.60309799],
       [-0.8774687 ]])

In [169]:
# # One-hot encoding
# y_train_categorical = to_categorical(y_train)
# y_test_categorical = to_categorical(y_test)
# y_train_categorical.shape

In [170]:
# first, create a normal neural network with 2 inputs, 6 hidden nodes, and 2 outputs
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=6, activation='relu', input_dim=2))
model.add(Dense(units=2, activation='softmax'))

In [171]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 6)                 18        
_________________________________________________________________
dense_13 (Dense)             (None, 2)                 14        
Total params: 32
Trainable params: 32
Non-trainable params: 0
_________________________________________________________________


In [172]:
# Compile the model
model.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=['accuracy'])

In [173]:
X_train_scaled.shape

(3478, 1)

In [174]:
y_train.shape

(3478, 1)

In [175]:
# Fit the model to the training data
model.fit(X_train_scaled, y_train, epochs=100, shuffle=True, verbose=2
)

Epoch 1/100


ValueError: in user code:

    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:747 train_step
        y_pred = self(x, training=True)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:212 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential_6 is incompatible with the layer: expected axis -1 of input shape to have value 2 but received input with shape [None, 1]


In [26]:
# Evaluate the model using the testing data
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

37/37 - 0s - loss: 220754.4062 - accuracy: 0.0112
Loss: 220754.40625, Accuracy: 0.011206896975636482


In [27]:
# import numpy as np
# new_data = np.array([[0.2, 0.3, 0.4]])
# print(f"Predicted class: {model.predict_classes(new_data)}")

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


ValueError: in user code:

    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  *
        return step_function(self, iterator)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
        outputs = model.predict_step(data)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
        return self(x, training=False)
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\berry\anaconda3\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:212 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential is incompatible with the layer: expected axis -1 of input shape to have value 2 but received input with shape [None, 3]
